### ISSUE TITLE
[Chore] Remove unused/duplicated code

### ISSUE THREAD

**Issue by olivierobert** [Prabeshpd/web-scraper-frontend#11]
## Issue

Upon going through the codebase, it appears that not all code is used, e.g., https://github.com/Prabeshpd/web-scraper-frontend/blob/14645f7abe38db98c4eeb97645b97c711cda2c77/src/utils/interceptors.ts#LL59C23-L59C65 (which also seem duplicated from `unauthorizedResponseHandlerInterceptor`)

**Comment by Prabeshpd** [comment]
I have removed the duplicated codes. 

The code was there for the `axios` httpFile object which was being used to send request for `application/formdata`. Since, now we are not uploading file to the server there is no need of that. If needed we can easily refactor the httpCreate for axios to pass custom headers as per need.
