### ISSUE TITLE
[Feature] Implement validation logic to process less than 100 keywords

### ISSUE THREAD

**Issue by olivierobert** [Prabeshpd/web-scraper-frontend#9]
## Issue

The current implementation does not prevent the processing of more than 100 keywords. The frontend only implement a file size limit:

https://github.com/Prabeshpd/web-scraper-frontend/blob/14645f7abe38db98c4eeb97645b97c711cda2c77/src/components/tag/Tags.tsx#L65-L70

However, it s a requirement:

![image](https://github.com/Prabeshpd/web-scraper-backend/assets/696529/93b11761-8867-4d86-83a5-4b178d71ec50)

## Expected

To improve the UX, the content of the CSV should be processed and validated before starting any scraping. The UI must display an error if a user uploads more than 100 keywords.

The backend could also implement another set of validations.

> **Note**
> Since the CSV upload must be limited to  https://github.com/Prabeshpd/web-scraper-frontend/issues/9, separating the parsing to another service does not bring much value, i.e., there is no risk of overloading the backend or frontend application. This requirement is there on purpose.

**Comment by Prabeshpd** [comment]
I was offloading the file parsing to backend as in future there may be need of processing large files. Plan was to use `S3` to store the data and send a event to `SQS` or `rabbitmq` with URL which would then process them.
Since, in the requirements we have a limitation of 100 words of csv file. It is safe to handle the parsing from the client side. In previous implementation we were assuming all the services to be on same computation device which will not be the case. So, updated the logic of handling csv files and implementation of validation from the client side.

I have implemented the changes

**Comment by olivierobert** [comment]
I have reviewed the PR and added a comment.
